### ISSUE TITLE
App crashes on Safari

### ISSUE THREAD

**Issue by iamyuu** [kentcdodds/fakebooks-remix#1]
I'm using Safari 15.2 and when I open the production deploy 
<details>
    <summary>I got a white blank page on the Remix</summary>
  <img src="https://user-images.githubusercontent.com/45778229/164580791-6e9fe4f5-ec00-4dde-b66f-6354b2245291.png" /> 
</details>

<details>
    <summary>but on the CRA, it runs fine</summary>
  <img src="https://user-images.githubusercontent.com/45778229/164580829-85cdd80d-fe44-4249-8586-da64aff6926e.png" /> 
</details>

**Comment by kentcdodds** [comment]
I think this is a React 18 bug. But I'll look into it. Thanks!

**Comment by nuno** [comment]
@kentcdodds @iamyuu,  I have cloned the repo and ran it on safari 15.4, Looks good, all seems to work as expected.
