### ISSUE TITLE
Missing site meta description

### ISSUE THREAD

**Issue by drewjs** [kentcdodds/fakebooks-remix#2]
Normally not a big deal for a demo, but in this case the sister app fakebooks-cra has a [meta description](https://github.com/kentcdodds/fakebooks-cra/blob/922760f272e0ad170d1b38d205143c7c73563091/public/index.html#L7-L10) set in the static html so it receives a higher Lighthouse score for SEO. Adding a description to the root of this project would be a more even comparison.

<details>
<summary>Lighthouse dings SEO score due to a missing meta description</summary>

![CleanShot 2022-05-06 at 14 53 07](https://user-images.githubusercontent.com/2999006/167221170-a91d9cb7-9d36-4dbb-ae4a-fb0777d48e13.png)
</details>

**Comment by kentcdodds** [comment]
Good point! Would you be interested in making a PR?
